version: '3.8'

services:
  model-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=5000
      - MODEL_DIR=/app/models
    volumes:
      - model-cache:/app/models
    # Automatically checks if service is healthy by calling the /health endpoint.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model-cache:
    driver: local