name: Release model-service

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse version info from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      - name: Install build tool
        run: pip install build

      - name: Build the Python package
        run: python -m build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-service:${{ env.version }}
          path: dist/
