name: Run unittests

on:
  push

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover
